### ISSUE TITLE
Stacker bypassing prop limit again?

### ISSUE THREAD

**Issue by JohnAtPG** [Mista-Tea/improved-stacker#2]
I'm not sure if I am the only one experiencing this but recently I noticed that stacker is sometimes bypassing the prop limit on my server again. I'm on the workshop version and haven't changed a thing at all.

It's happened a few times but I cannot reproduce it currently. 

If there is anyway I can help, let me know. I know this may be useless but I've seen stacker bypass prop limit at least 3 times in the past week but completely random.

**Comment by Mista-Tea** [comment]
I've realize it's been a very long time since this issue was last addressed, and I apologize.

I haven't received any messages of others having issues with Stacker bypassing prop limits. I hate to simply conclude that the addon you are using isn't handling prop limits correctly, but I can't think of any other reason.
