### ISSUE TITLE
The gets put under a category called "New Category" and is un-usable.

### ISSUE THREAD

**Issue by CR4KH34D8U2** [Mista-Tea/improved-stacker#23]
Under the category the tool is called "stacker_improved" and when I click on it, where it's supposed to tell you how to use it. Instead it just says "#tool.stacker_improved.0" and where the name is supposed to be, it says "#tool.stacker_improved.name" and where the description would be, it says "#tool.staker_improved.desc". Neither left click nor right click do a thing. I really liked using this tool but now I can't. Would be great if you could help!

**Comment by Mista-Tea** [comment]
1. Are you using the Workshop version of the tool, or directly from here on GitHub?
2. Does the problem still persist after rejoining your server or restarting Garry's Mod?

I haven't made any changes to the tool since May (Workshop) or February (Github). I loaded into singleplayer using both versions and have not experienced the issue you are having.

**Comment by CR4KH34D8U2** [comment]
What do you think could be a conflicting addon? I am also using the Workshop version and yes the problem still persists after rejoining my server or restarting Garry's Mod. I'd hate to have to disable all my add-ons and enable them one by one to see which one conflicts.

**Comment by Mista-Tea** [comment]
Do you remember when you started having this issue?

You could potentially unsub and resub to the tool, and/or delete the GMA file in Steam/steamapps/common/GarrysMod/garrysmod/addons/improved_stacker_264467687.gma and have it redownload.

Unfortunately, I don't really know of other ways to help you. If you've only been going to singleplayer or a single multiplayer server, you may want to try a different multiplayer server that also has the tool and see if the problem happens there too.

Otherwise, if you have to go through your other addons, you could start with the ones that have updated the most recently (you can sort the GMAs by `Date Modified` in the addons folder) or the ones you subscribed to most recently around the time you started having this issue.
