### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by PolSpock** [Mista-Tea/improved-stacker#27]
Hi, sometimes when player use the tool, the server get this error :

[ERROR] addons/tool_improved_stacker/lua/weapons/gmod_tool/stools/stacker_improved.lua:417: bad argument #1 to 'WriteUInt' (number expected, got function)
1. WriteUInt - [C]:-1
2. SendError - addons/tool_improved_stacker/lua/weapons/gmod_tool/stools/stacker_improved.lua:417
3. LeftClick - addons/tool_improved_stacker/lua/weapons/gmod_tool/stools/stacker_improved.lua:630
4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:227

However I don't know how to reproduce it :/
Regards

**Comment by Mista-Tea** [comment]
I'll try to look into it :) Might be kind of hard without knowing how to replicate it.

**Comment by dvdvideo1234** [comment]
The line `net.WriteUInt( notify or NOTIFY_ERROR, MIN_NOTIFY_BITS )` seems to have the `notify` value globally,  which is not defined in the current file. This presents a global value injection of whatever is stored in `notify`. When this value is set and it is different than `false` or `nil` it will be taken with priority to `NOTIFY_ERROR` for all other types, including the `function` type, which the user above experiences. ;)

**Comment by Mista-Tea** [comment]
It's hard to find the change history for that specific function, but I believe the original implementation or at least the intention was that TOOL:SendError() was actually TOOL:SendNotif(notify) and that if no NOTIFY_* parameter (notify) was passed, it would default to error.

Anyway, thanks for pointing out this mistake. The notify parameter doesn't even exist and doesn't need to exist since it's always a NOTIFY_ERROR anyway, so I'll accept the related PR.
