### ISSUE TITLE
Bug with vectors

### ISSUE THREAD

**Issue by seynz** [Mista-Tea/improved-stacker#39]
Briefly in certain vectors on the map, prop is created from World. If this vector is somehow transmitted through the network, then it is compressed and therefore inaccuracy same with server-> client prop at the client can have compressed coordinates a little decimal precision is lost.

**Comment by dvdvideo1234** [comment]
Is the precision misalignment form the sliders having a finite symbols after the decimal point. 
As I recall [`cpanel:AddControl(...)`](https://wiki.facepunch.com/gmod/ControlPanel:AddControl)  does not utilize larger precision than 3 places after the decimal point and is being deprecated not like the new [non-deprecated API](https://wiki.facepunch.com/gmod/DForm:NumSlider):

*slider:
  *type (optional string, if equals "float" then 2 digits after the decimal will be used, otherwise 0)
  *label (def: "Untitled")
  *command
  *min (def: 0)
  *max (def: 100)
  *help (boolean, see above)

**Comment by seynz** [comment]
I think : somehow transmit this vector through the network, then it is compressed and therefore inaccuracy
same with server-> client
prop at the client can have compressed coordinates
a little decimal precision is lost

**Comment by seynz** [comment]
This happens in some areas of our map. For example, on this vector - Vector (-8650.4150390625, 10331.444335938, -556.65972900391)

**Comment by Mista-Tea** [comment]
So if I'm understanding correctly, part of the issue may arise from me still using the `DForm:AddControl` functionality instead of the more explicitly named DForm control methods, and potentially from compression/precision lost due to the server reading networked float vector (x/y/z) values from the client e.g. via the offset/rotate convars?

```lua
function TOOL:GetOffsetX()      return math.Clamp( self:GetClientNumber( "offsetx" ), -cvarMaxOffX:GetFloat(), cvarMaxOffX:GetFloat() ) end
function TOOL:GetOffsetY()      return math.Clamp( self:GetClientNumber( "offsety" ), -cvarMaxOffY:GetFloat(), cvarMaxOffY:GetFloat() ) end
function TOOL:GetOffsetZ()      return math.Clamp( self:GetClientNumber( "offsetz" ), -cvarMaxOffZ:GetFloat(), cvarMaxOffZ:GetFloat() ) end
function TOOL:GetOffsetVector() return Vector( self:GetOffsetX(), self:GetOffsetY(), self:GetOffsetZ() ) end
---------------------------------------------------------
function TOOL:GetRotateP()     return math.Clamp( self:GetClientNumber( "pitch" ), -MAX_ANGLE, MAX_ANGLE ) end
function TOOL:GetRotateY()     return math.Clamp( self:GetClientNumber( "yaw" ),   -MAX_ANGLE, MAX_ANGLE ) end
function TOOL:GetRotateR()     return math.Clamp( self:GetClientNumber( "roll" ),  -MAX_ANGLE, MAX_ANGLE ) end
function TOOL:GetRotationAngle() return Angle( self:GetRotateP(), self:GetRotateY(), self:GetRotateR() ) end
```

Is it possible that switching to DForm:NumSlider and then setting/reading the client's offset/rotate values as strings rather than floats would prevent the compression/loss of precision? Or is there some other approach that I should also take? I unfortunately haven't deal with precision loss much in or out of GMod.

**Comment by dvdvideo1234** [comment]
I think the new Gmod 13 API allowing more than 2 decimal places can be utilized quite good in this case, as for the rotation and translation you are using `self:GetClientNumber( "convar_short_name" )` which reads the already rounded to to decimal places value. Here is [how I use it in TA][1] and I bet you can add a canvas to tell you how precise you want the numsilers to be, because it is only an integer parameter ;)

[1]: https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/weapons/gmod_tool/stools/trackassembly.lua#L1389

**Comment by Mista-Tea** [comment]
@seynz Can you try out the [dev_decimal_precision branch](https://github.com/Mista-Tea/improved-stacker/tree/dev_decimal_precision) and see if this addresses this issue?

Changes: https://github.com/Mista-Tea/improved-stacker/commit/4df83c3d6faae92dc39c0d65091569a03ef2467f

I've added `stacker_improved_offset_decimals` and `stacker_improved_rotate_decimals` convars to allow the you to change the precision on the fly, so you could set it to whatever you want (default is 2 to match existing behavior).

**Comment by seynz** [comment]
Not worked

**Comment by seynz** [comment]
@Mista-Tea can you contact? (discord: saynz # 5393)
