### ISSUE TITLE
Stacker crashes Server

### ISSUE THREAD

**Issue by powerup216** [Mista-Tea/improved-stacker#4]
Hi. I just downloaded your addon and it works great. But there is an exploit many users are using with this stacker tool to crash servers. A player could stack props one at a time until they have a lot and then unfreeze the props resulting in server crash. I believe it could be fixed if you added a stacker prop limit, which would minimize the amount of damage a exploiter could do on a server. Thanks for reading.

**Comment by Mista-Tea** [comment]
Sorry for the late response, @powerup216.

I've committed a patch to the new dev branch here on GitHub that should help prevent this issue for you. You can use an SVN client like TortoiseSVN to checkout to your server or simply download the addon as a .zip folder. If you can test it out and report back to here with any problems or suggestions, that would be terrific. I've tried testing it as much as possible on my Sandbox server but it is likely I've missed something. See below for the details.
------------------------------------------
You can now use ```stacker_max_total``` (or ```stacker_set_maxtotal``` if you do it from your client) to limit the total number of stacker props that a player can have spawned out at any given time.

The default right now is -1 (no limit) so that it doesn't interfere with servers. However, in your case you can set it to something within reason and it should block players from spawning more stacker props than the limit you set.

Just be aware that by setting this limit, you are going to be restricting legitimate players from using the Stacker tool properly. Setting the limit too low means the tool essentially becomes worthless. Setting it too high and nothing will change with the crashes. You will need to find a balance between both of them, and possibly resort to the stacker_force_nocollide cvar.

**Comment by Mista-Tea** [comment]
@powerup216, have you been able to give this a try yet?

**Comment by Mista-Tea** [comment]
It's been a while since this was opened. Do you have any updates, @powerup216 ?

**Comment by Mista-Tea** [comment]
I'm going to close this for now. Please feel free to reply back if you have any further issues.
